package dev.wceng.sufei.ui.theme
import androidx.compose.ui.graphics.Color

// ==================== 浅色主题 — 中国风暖色宣纸美学 ====================
// primary: 妃红色系（印章、收藏、强调元素）
// secondary: 墨棕色系（次级文字、辅助元素）
// tertiary: 靛青色系（分类标签、词牌标识）
// background / surface: 暖宣纸色调

val primaryLight = Color(0xFFD08878)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFDCD1)
val onPrimaryContainerLight = Color(0xFF3F1A10)
val secondaryLight = Color(0xFF6B5B4F)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFF4E6D9)
val onSecondaryContainerLight = Color(0xFF231A10)
val tertiaryLight = Color(0xFF5B7B8A)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFD5EAF2)
val onTertiaryContainerLight = Color(0xFF0E2E3A)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF7F2E8)
val onBackgroundLight = Color(0xFF1E1915)
val surfaceLight = Color(0xFFFCFAF5)
val onSurfaceLight = Color(0xFF1E1915)
val surfaceVariantLight = Color(0xFFE8E0D5)
val onSurfaceVariantLight = Color(0xFF4A4038)
val outlineLight = Color(0xFF7A7068)
val outlineVariantLight = Color(0xFFCBC0B5)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF33302A)
val inverseOnSurfaceLight = Color(0xFFF2ECE2)
val inversePrimaryLight = Color(0xFFF0B8A8)
val surfaceDimLight = Color(0xFFE4DED6)
val surfaceBrightLight = Color(0xFFFCFAF5)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF8F4EE)
val surfaceContainerLight = Color(0xFFF2EDE7)
val surfaceContainerHighLight = Color(0xFFEDE7E1)
val surfaceContainerHighestLight = Color(0xFFE7E1DB)

// ==================== 深色主题 — 暖灰墨色系 ====================

val primaryDark = Color(0xFFF0B8A8)
val onPrimaryDark = Color(0xFF4A1D10)
val primaryContainerDark = Color(0xFF6B3D2E)
val onPrimaryContainerDark = Color(0xFFFFDCD1)
val secondaryDark = Color(0xFFD5C5B4)
val onSecondaryDark = Color(0xFF3A2D22)
val secondaryContainerDark = Color(0xFF514338)
val onSecondaryContainerDark = Color(0xFFF4E6D9)
val tertiaryDark = Color(0xFFB0D5E0)
val onTertiaryDark = Color(0xFF1A3A44)
val tertiaryContainerDark = Color(0xFF435860)
val onTertiaryContainerDark = Color(0xFFD5EAF2)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1A1614)
val onBackgroundDark = Color(0xFFEBE2D8)
val surfaceDark = Color(0xFF1E1B18)
val onSurfaceDark = Color(0xFFEBE2D8)
val surfaceVariantDark = Color(0xFF4A4038)
val onSurfaceVariantDark = Color(0xFFD0C6BB)
val outlineDark = Color(0xFFA29890)
val outlineVariantDark = Color(0xFF4A4038)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEBE2D8)
val inverseOnSurfaceDark = Color(0xFF33302A)
val inversePrimaryDark = Color(0xFFD08878)
val surfaceDimDark = Color(0xFF1A1614)
val surfaceBrightDark = Color(0xFF302B27)
val surfaceContainerLowestDark = Color(0xFF100D0B)
val surfaceContainerLowDark = Color(0xFF1E1B18)
val surfaceContainerDark = Color(0xFF221F1C)
val surfaceContainerHighDark = Color(0xFF2D2A26)
val surfaceContainerHighestDark = Color(0xFF383531)
